<a href="https://colab.research.google.com/github/Juhi0313/fastapi-course/blob/main/pytorchcourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch numpy scikit-learn

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

False

In [ ]:
torch.cuda.is_available()

NameError: name 'torch' is not defined

In [ ]:
!pip install torch numpy scikit-learn


In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

Tensors


they r basically a word for high dimensional array. numpy only works on cpu

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tensor = torch.tensor([[1,2,3], [4,5,6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
arr.sum()

np.int64(21)

In [ ]:
tensor.sum()

tensor(21)

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
np.random.random((2,4))

array([[0.67066512, 0.75479328, 0.02692488, 0.33939554],
       [0.70319612, 0.07012983, 0.3812497 , 0.24256326]])

In [ ]:
torch.rand((2,4))

tensor([[0.5831, 0.4627, 0.6569, 0.2839],
        [0.7294, 0.4109, 0.6580, 0.2800]])

In [ ]:
arr.shape
arr.dtype

dtype('int64')

In [ ]:
arr.shape


(2, 3)

In [ ]:
arr.device

'cpu'

In [ ]:
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
tensor = tensor.to('cuda')

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [ ]:
tensor.sum()

tensor(21)

In [ ]:
print(tensor.sum())


tensor(21)


In [ ]:
print(tensor.sum().device)

cpu


In [ ]:
print(torch.cuda.is_available())

True


In [ ]:
print(torch.cuda.get_device_name(0))

Tesla T4


In [ ]:
print(tensor.sum())

tensor(21)


In [ ]:
print(tensor.sum().device)

cpu


In [ ]:
print(tensor.device)  # probably shows 'cpu'

cpu


In [ ]:
tensor = tensor.to('cuda')
print(tensor.device)        # should now show cuda:0
print(tensor.sum().device)  # cuda:0

cuda:0
cuda:0


In [ ]:
print(tensor.sum())        # tensor(21, device='cuda:0')
print(tensor.sum().device) # cuda:0

tensor(21, device='cuda:0')
cuda:0


In [ ]:
import torch

In [ ]:
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

f = 3 * a**3 - b**2

In [ ]:
f


tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [ ]:
f.backward(gradient=torch.tensor([1,1]))

In [ ]:
print(a.grad)

tensor([36., 81.])


In [ ]:
print(b.grad)

tensor([-12.,  -8.])


Neural Networks

In [ ]:
import torch
import torch.nn as nn ##nn = neural networks
import torch.nn.functional as F #functional is used for activation functions. these r the functions that r applied after the layers to break linearity.
import torch.optim as optim #optim for optimizers we'll use
from torch.utils.data import DataLoader, TensorDataset


from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = load_breast_cancer(return_X_y=True) #X means info abt tumour and y means malignant or benign
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



In [ ]:
X_train_scaled

array([[-0.41439951, -0.25635499, -0.37499049, ...,  0.42597322,
         0.56517715,  1.09451257],
       [-0.00232133, -0.48761046, -0.07562399, ..., -0.5287089 ,
        -0.60688437, -0.95795005],
       [-0.51668842, -0.78660742, -0.5386668 , ..., -1.00860756,
        -0.67485399, -1.12508151],
       ...,
       [-0.75049165, -0.1909494 , -0.77400449, ..., -0.74060214,
        -0.24714272, -1.02524391],
       [-0.95506947,  0.63362817, -0.9643948 , ..., -0.59474147,
         0.1258613 , -0.37712685],
       [ 1.7921184 ,  1.76654637,  1.78799611, ...,  1.58076812,
         0.63314677, -0.39367452]])

In [ ]:
y_train

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,

In [ ]:
# now we'll turn this into tensors and then we want to use a data loader to easily load the data for our training process
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()

y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)


In [ ]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)

In [ ]:
X_train_scaled_tensor.shape

torch.Size([455, 30])

In [ ]:
# now we can turn this into loader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [ ]:
#we'll create neural network as a class. this is the structure of neural networks
class BCNet(nn.Module):
  def __init__(self):
    super(BCNet, self).__init__()
    self.fc1 = nn.Linear(30, 64) #this is fully connnected dense linear layer. 64 is the neurons we want/outputs we want
    self.fc2 = nn.Linear(64, 32) #this layer takes output of previous layer as input
    self.fc3 = nn.Linear(32, 1) #1/single value is the actual output (0 or 1)

  #to put data in this structure:
  def forward(self, x): #x is the input
    #x = self.fcl(x) means we take this input vector/matrix if batches, we feed it through the network and get the result of taking the input and multiplying with weights of fully connected layer 1, adding the bias and getting some output.
    #in order to break the linearity:
    x = F.relu(self.fc1(x)) #relu is the activation function. this gives new value of x
    x = F.relu(self.fc2(x))
    x = torch.sigmoid(self.fc3(x)) #we used sigmoid because it produces value bw 0 and 1

    return x
    #this was the forward pass of our network



In [ ]:
model = BCNet()

In [ ]:
#since we r doing binary classification in this/Loss function:
criterion = nn.BCELoss() #bcloss = binary cross entropy loss
optimizer = optim.Adam(model.parameters(), lr=0.001) #lr = learning rate

In [ ]:
#now we'll define training loop/train the network
epochs = 20 #we r going to do 20 iterations on the same data

for epoch in range(epochs):
  model.train() #put the model in training model
  running_loss = 0.0

  #now we'll interate over our data loader to get individual batches
  for x_batch, y_batch in train_loader:
    #we r going to feed data thorugh our model, get prediction (which in beginning will be completley random), and then take true classification and calculate the loss (how wrong that model) and take that loss function and back-propogate (take derivative of) the loss and try to find minimum in that function (decent local minimum)
    optimizer.zero_grad() #remove gradients
    preds = model(x_batch)
    loss = criterion(preds, y_batch)
    #this was raw loss. now we need to back-propogate it

    loss.backward() #automatic differentiation
    optimizer.step() #update weights
    running_loss += loss.item() #keeping track of running loss aswell

  print(f'Epoch {epoch + 1}: Loss was {running_loss/len(train_loader)}')




Epoch 1: Loss was 0.025566237419843672
Epoch 2: Loss was 0.02962244627997279
Epoch 3: Loss was 0.022208918491378425
Epoch 4: Loss was 0.022292450504998364
Epoch 5: Loss was 0.019993208736802142
Epoch 6: Loss was 0.020229222097744543
Epoch 7: Loss was 0.01901067964111765
Epoch 8: Loss was 0.016361908688365172
Epoch 9: Loss was 0.016419476938123505
Epoch 10: Loss was 0.014347698236815632
Epoch 11: Loss was 0.013064966280944645
Epoch 12: Loss was 0.019706994605561096
Epoch 13: Loss was 0.01592194402279953
Epoch 14: Loss was 0.021186351000020903
Epoch 15: Loss was 0.010072217524672548
Epoch 16: Loss was 0.011530412915938844
Epoch 17: Loss was 0.00902350183193145
Epoch 18: Loss was 0.008154847822152079
Epoch 19: Loss was 0.013716951773191492
Epoch 20: Loss was 0.007269124768208712


In [ ]:
#now we'll define evaluation logic (how can we evaluate this model on unseen data)
with torch.no_grad():
  model.eval()
  preds = model(X_test_scaled_tensor)
  loss = criterion(preds, y_test_tensor)

  accuracy = (())

**Autograd**


In [ ]:
import torch


In [ ]:
#creating tensor
x = torch.tensor(3.0, requires_grad=True) #by default requires_grad is false but we keep it true when we want to calculate the derivative of this tensor

In [ ]:
y = x**2

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)